### ISSUE TITLE
question about license

### ISSUE THREAD

**Issue by allusernamestakenexceptthis** [bsimser/Micropolis#1]
Correct me if I'm wrong.  just want to be sure.  if this is derivative of micropolis and the original licensed under GPL, then MIT license is incompatible and should be invalid no?  just want to be on the safe side. otherwise this is really nice.

**Comment by bsimser** [comment]
Thanks @allusernamestakenexceptthis I'll check with Don on the licensing. I think we're okay because we released some other derivatives under the non-GPL licenses and they were fine, but I'll check and see with him and might have to take to others as well (EA, legal, etc.)

**Comment by ancestral** [comment]
allusernamestakenexceptthis is right. You need to license this as GPLv3. You can license your non-derivative content as something more permissive, but there are certain attribution and distribution restrictions that are a part of the GPL that MIT doesn’t ask for.

**Comment by bsimser** [comment]
Thanks for the feedback guys. I've fixed the license and put it back to the original Micropolis GPL (GPLv3 with additional terms as per GNU GPL Section 7). Closing this issue now.
